### PR TITLE
Feature/server split

### PR DESCRIPTION
**Pull request by zGrav**
splits api & routes into own workspace/server

### CODE REVIEW

**Comment by thiemok** [comment]
Currently breaks on windows.
We could fix this by adding something like [npm-run-all](https://yarnpkg.com/en/package/npm-run-all), this will correctly run yarn scripts (using yarn) in parallel or sequence.

I also prepared a second docker container for the backend, but have some trouble connecting them.

**Comment by zGrav** [comment]
I'm down for patching it with npm-run-all if @maddrag0n thinks it's the best solution.

**Comment by thiemok** [comment]
Travis broken because of node v10 release, we might have to just wait.

**Comment by thiemok** [comment]
`yarn run run:docker` does not stop the containers on exit on windows, this might be a docker for windows issue though

**Review by maddrag0n — APPROVED** [review]
lgtm

**Pull request merged**
