### PR TITLE
Feature/material ui next

### LINKED ISSUE #19: update to material-ui@next (1.0.0-beta.38)
# tasks

- [x] update deps
- [x] migrate components

# why?

material-ui@^0.20.0 still depends on react-transition-group@^1.0.0 which can cause console spam when using react@^14.0.0 (because of adding unsupported props to HTMLElements). This can lead to broken transition behavior (e. g. reproducible when using react components that use material-ui dialogs wrapped in a ngReact directive)

material-ui@next uses react-transition-group@^2.0.0 where that is fixed.

### PR DESCRIPTION
**Pull request by zGrav**
Closes #19 .

### CODE REVIEW

**Review by maddrag0n — APPROVED** [review]

**Comment by maddrag0n** [comment]
@zGrav after merging the bundle does not serve anymore… ideas?

**Review by maddrag0n — CHANGES_REQUESTED** [review]
after merge bundle returns 404 / wrong mime type

**Comment by zGrav** [comment]
Shall check

**Comment by zGrav** [comment]
Fixed, 0.20.0 snuck back in with the merge it seems.

After this, we need to update to @material-ui/icons and @material-ui/core

**Comment by zGrav** [comment]
Merged

**Pull request merged**
