### PR TITLE
chore: package updates

### PR DESCRIPTION
**Pull request by zGrav**
No codebase changes, quite a few things deprecated on material-ui's side and probably new React/Redux/Webpack optimizations to be done.

### CODE REVIEW

**Comment by zGrav** [comment]
a lot better now.

**Comment by thiemok** [comment]
I seem to have problems even start your branch
Screenshot from 2019-04-28 12:22:07

**Comment by zGrav** [comment]
@thiemok whoops, apparently didn't save my last commit somehow... pull and retry pl0x

**Comment by thiemok** [comment]
@zGrav looks good so far, but it seems to have problems with node 12 on travis, can you check that?

**Comment by zGrav** [comment]
@thiemok noticed, running a local build on my end to see what's up, seems to be node-sass

EDIT: ~maybe node-gyp~ actually fsevents

**Comment by zGrav** [comment]
currently broken in node 12 native builder, will be fixed soonTM.

**Comment by thiemok** [comment]
Is there an issue for that that you can link?

**Comment by zGrav** [comment]
https://github.com/fsevents/fsevents/pull/271 https://github.com/nodejs/nan/issues/849 @thiemok

**Review by thiemok — DISMISSED** [review]
Lgtm

**Comment by thiemok** [comment]
Up to you if you want to merge

**Comment by zGrav** [comment]
Will wait and check again @thiemok

**Comment by zGrav** [comment]
jsdoc-webpack-plugin also broken in v12. If no updates on it surge (and if unrelated with fsevents), I might consider building own implementation.

**Comment by zGrav** [comment]
for some reason, everything is green now regarding current node version @thiemok wtf 🙈

**Comment by zGrav** [comment]
Reasoning behind using a non-official jsdoc/docdash: https://github.com/jsdoc3/jsdoc/pull/1641

Currently the dep for requizzle is bad, this man has removed it but jsdoc hasn't put it officially yet, even on their "next" branch and this approach will break almost (if not all) current existing templates (docdash,etc).

This also led to me forking docdash/jsdoc and changing it slightly to support these changes.

@maddrag0n @thiemok this should now be good to go

**Comment by zGrav** [comment]
Also confirmed working on 12.1.0

**Review by thiemok — DISMISSED** [review]
lgtm, if you take care of removing that fork in the future once its no longer necessary

**Comment by zGrav** [comment]
More stuff, non-breaking changes, will merge post-travis.

I have a watch on the issue

**Pull request merged**
