### PR TITLE
2018 garage sale

### PR DESCRIPTION
**Pull request by maddrag0n**
# Story

As a developer I want to have a stable and up-to-date version of this boilerplate.

# Specific requirements

This is mostly about cleaning up, updating and making the boilerplate more lean and elegant. On the feature side the only big additional feature will be react-styleguidist.

**remaining and new issues now live in the [release 1.0.0 project board](https://github.com/bitchcraft/reactjs-boilerplate/projects/1)**

history of tasks (before introduction of project board)
> * [x] clean webpack.config
> * [x] consolidate babel settings
> * [x] clean and remove unused deps
> * [x] migrate to workspaces
> * [x] deprecate redundant static html and add build step for template
> * [x] migrate from make file to package.json scripts
> * [x] change dockerfile to accomodate for changes to project structure
> * [x] update eslint/airbnb/flow etc.
>   * [x] fix flow (flow seems to be pretty permissive and does not error much)
> * [x] update ReactJS, redux, react-router etc.
> * [x] deprecate PropTypes for flow
> * [x] migrate uuid to uuid/v4
> * [x] add styleguidist
> * [x] add nodemon (watch only `./server/**/*.{js|json}` and `./common/**/*.{js|json}`!)
> * [x] make webpack faster on dev builds (https://github.com/maddrag0n/reactjs-boilerplate/pull/5/commits/58037c34ddcce5910482846c7d055197e13942ba should of fixed this)
> * [x] make docker build faster
> * [x] update express and related (helmet, morgan, body-parser, etc.)
> * [x] add jsdoc parser with docdash template
>   * [x] add docblocks (otherwise you get no docs 🤔)
> * [x] update material-ui (not to `@next`)
> * [x] replace npm-zepto with jquery
> * [x] add jsdocblocks to source files
>   * [x] /app/services
>   * [x] /common/tools
>   * [x] /app/reducers
>   * [x] /app/actions
>   * [x] /server
> * [x] rewrite build scripts in node to support windows
> * [x] add cli linting script
> * [x]  babel-minify for env "production" (**WARNING**: mangle is currently disabled in babel 6 due to a bug which is fixed in the upcoming babel 7 release, please remove the minify opts then.)
> * [x] publish common/tools files as npm packages and add as yarn packages
>   * [x] log —> [unicorn-logger](https://yarn.pm/@bitchcraft/unicorn-logger)
>   * [x] object keys converter —> [ocake](https://yarn.pm/@bitchcraft/ocake)
>   * [x] date to ISO string (@maddrag0n)
>   * [x] style injector (@maddrag0n)
> * [x] add missing flow types to files
>   * [x] reducers/**/*
>   * [x] actions/**/* (also create a FluxStandardAction flow typedef in common/flow, see https://github.com/redux-utilities/flux-standard-action for spec)
>   * [x] services/**/*
>   * ignore tools (they are gonna be moved out anyways)
>   * [x] server/**/*
>   * [x] constants/**/*
>   * [x] authWrapper conflicts (User/AuthRequest)

# QA Notes

* test dev build
* test all package.json scripts
* test docker build

### CODE REVIEW

**Comment by maddrag0n** [comment]
@zGrav can you look into what is causing the `parseQuery() will be replaced with getOptions() in the next major version of loader-utils.` webpack warnings and if we can somehow solve that?

**Comment by zGrav** [comment]
Yup, outdated babel-loader, updated to latest stable version which is 7.1.3, warning stopped.

**Comment by zGrav** [comment]
Immutable is throwing a flow error, hopefully will be fixed in the upcoming 4.0 release. 

Issue already exists in Immutable's repo: https://github.com/facebook/immutable-js/issues/1435

**Comment by zGrav** [comment]
~~FYI: small issue remains with current mat-ui impl, onTouchTap/onClick on buttons does nothing atm, I might of missed something in the new docs where it refers Button/ButtonBase.~~

Fixed in https://github.com/bitchcraft/reactjs-boilerplate/pull/5/commits/dc01e36ae7494abcd98f10d13e9b711b9d770ab1

**Comment by thiemok** [comment]
@zGrav can you verify if this works with latest chrome? Mine seems to have problems loading the site (Chrome 67)

**Comment by thiemok** [comment]
Everything else is working correctly.

## Fixes needed before merge
* [x] Verify functionality with chrome
* [x] Fix styleguide (#24)

**Comment by zGrav** [comment]
@thiemok do you mean loading the page?

Works for me even in incognito

**Comment by thiemok** [comment]
yes, can you try on win or linux too?

**Comment by zGrav** [comment]
on it

**Comment by zGrav** [comment]
Working on both win and *nix as well, what error are you seeing @thiemok ?

**Comment by thiemok** [comment]
404 on bundle.js dunno whats happening there, maybe just a glitch. Works with firefox.

**Review by thiemok — APPROVED** [review]

**Comment by zGrav** [comment]
Merged

**Pull request merged**
